### ISSUE TITLE
Incomplete PATH in scripts for the three stages

### ISSUE THREAD

**Issue by linux40** [void-linux/void-runit#109]
`/etc/runit/{1,2,3}` set PATH as `/usr/bin:/usr/sbin`. However, in a fresh installed voidlinux on aarch64 machines via rootfs, many binaries locates at `/sbin` including `mount`, and this results failing to boot. The complete value should be:
```
/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin
```

**Comment by classabbyamp** [comment]
> in a fresh installed voidlinux on aarch64 machines via rootfs

how did you install this? was it from a non-aarch64 computer?

**Comment by classabbyamp** [comment]
it shouldn't matter what debian had if you're booting void.

two possibilities I can think of:
- the symlinks are created during package configuration and that somehow didn't happen
- something weird happened during extraction of the rootfs tarball (perhaps it was extracted on a filesystem that doesn't support symlinks?)
