### ISSUE TITLE
Missing folder

### ISSUE THREAD

**Issue by pingpongterminator300** [void-linux/void-runit#116]
Trying to start services like dbus, bluetooth in void linux arm rootfs, but its missing `/run/runit/` folder with all content. So it cant start because 
```
warning: /etc/sv/dbus: unable to open supervise/ok: file does not exist
```
Its not booted, im running its in chroot because of my needs

**Comment by Vaelatern** [comment]
Is runit running?

**Comment by pingpongterminator300** [comment]
Its shown on processes list
```
sudo ps uaxf | grep runit

testuser   11742  0.0  0.0   6384  2152 pts/0    S+   17:42   0:00                      \_ grep --color=auto runit
```

**Comment by classabbyamp** [comment]
that's your grep not runit

**Comment by pingpongterminator300** [comment]
So its not running
