### ISSUE TITLE
Is there a reason to do 'udevadm settle' vs allowing it to settle in background?

### ISSUE THREAD

**Issue by laserbat** [void-linux/void-runit#15]
From this discussion: https://github.com/rickysarraf/laptop-mode-tools/issues/137

It seems that it would be better to allow udev settle in background while system is booting and use something like `udevadm settle -t 0 || exit` for services that absolutely must start after all devices are settled.

**Comment by Vaelatern** [comment]
Seems like an optimization that makes things less stable.

**Comment by rickysarraf** [comment]
You should not use `udevadm settle` in the background. That forfeits the purpose.. I agree with @Vaelatern that this is an optimization that makes things less stable. **Dependent Device Discovery** should be done very very early. And for everything asynchronous, you have your `init` manager.

**Comment by Duncaen** [comment]
But runit does not provide the same kind of dependency management as systemd.
runit services do not mount filesystems and the early system initialization is done done parallel.
The scripts wait for udev to settle in `/etc/runit/core-services/02-udev.sh` and then mount filesystems other than root in `/etc/runit/core-services/03-filesystems.sh`, some of them which might be crucial to a usable system, `/home` as example.

**Comment by laserbat** [comment]
Okay, thank you all for explanations
