### ISSUE TITLE
What should vlogger do if tag is not specified?

### ISSUE THREAD

**Issue by CMB** [void-linux/void-runit#3]
Currently it fails and re-execs.  However, if this is intended to be
a drop-in replacement for logger, we have existing services that call
logger without a tag.  E.G., dcron/log.

**Comment by Duncaen** [comment]
Hmm I see, I guess the default tag you introduced that I reverted is the best way to go in this case.
Using the username like `logger(1)` is good too, but I'm not sure if this is worth it.

**Comment by CMB** [comment]
I think a default tag like vlogger is probably just good enough.
Having the username might be nice if you want to be fully compatible with
logger, but AFAIK all of our logging services that use logger run as root,
so it's not really worth the effort.

We can probably close this.

**Comment by Duncaen** [comment]
Yes, I added "vlogger" again as default, POSIX only specifies that `logger` should concenate strings on the command line and send it to the system log, everything else is an extension.
With the `s`, `i` and `f` flag its not compatible with `logger` on the BSDs.

**Comment by chneukirchen** [comment]
I'd at least use user.notice by default, like logger:

```
2018-06-25T11:27:29.79490 user.notice: leah: foo bar baz              
2018-06-25T11:27:32.36362 daemon.info: vlogger: foo bar baz
```
