### ISSUE TITLE
Support disabling 03-filesystems.sh

### ISSUE THREAD

**Issue by matthias-t** [void-linux/void-runit#43]
I have dracut configured to mount all my filesystems, so I would like to disable the `03-filesystems.sh` core service. Could something like:

```sh
[ -e /etc/stage-1-no-mount ] && exit
```

be added to the start of the script?

**Comment by leahneukirchen** [comment]
You can use noextract= in your xbps config to not install that file.

**Comment by matthias-t** [comment]
Thank you!
