### ISSUE TITLE
how to start 'cups' service?

### ISSUE THREAD

**Issue by erdosnew** [void-linux/void-runit#44]
hi, I couldn't figure out how to start a service like 'cups' in void linux.  I've looked up documentation and tried the following:
sh-5.0# sv status cupsd
fail: cupsd: unable to change to service directory: file does not exist

it seems that 'cups' is in /etc/sv/cupsd, tried the following as well. 
[erdos@quantum ~]$ sudo sv up /etc/sv/cupsd
warning: /etc/sv/cupsd: unable to open supervise/ok: file does not exist

so how to start a service?

**Comment by ericonr** [comment]
You can find instructions for it here: https://docs.voidlinux.org/config/services/#enabling-services
