### ISSUE TITLE
Encrypted ZFS volumes not mounted on boot

### ISSUE THREAD

**Issue by dm17** [void-linux/void-runit#62]
Not sure if it is a bug or a feature. Either way, what's the correct way to accomplish in Void?

This issue is the same as:
https://github.com/openzfs/zfs/issues/8750

**Comment by ericonr** [comment]
Isn't this https://github.com/void-linux/void-runit/issues/54 ?

**Comment by dm17** [comment]
Thanks, so I just added the command I was using (zfs mount -a -l) to /etc/rc.local
