### ISSUE TITLE
03-filesystems.sh activates all LVM LVs instead of just those whitelisted

### ISSUE THREAD

**Issue by subsonik** [void-linux/void-runit#64]
Hi,

03-filesystems.sh contains "vgchange --sysinit -ay". -ay is only supposed to be used by the user when they want to activate all logical volumes. 

Init scripts should use "-a ay", which respects the auto_activation_volume_list option in lvm.conf, and only activate LVs that the user has whitelisted as auto-activated.

This is mentioned in the vgchange man page for the -a switch:

```
ay specifies autoactivation, in which case an
LV is activated only if it matches an item in lvm.conf
activation/auto_activation_volume_list.  If the list is not set,
all LVs are considered to match, and if if the list is set but
empty, no LVs match.  Autoactivation should be used during
system boot to make it possible to select which LVs should be
automatically activated by the system.
```

Thanks!

**Comment by heliocat** [comment]
This wasn't caught because the default config catches the "no auto_activation_volume_list" base case where `-a y` and -a ay` have the same behavior. For most people the change should be entirely transparent and for folks with custom vg activation setups it will see it work as expected.
