### ISSUE TITLE
Discussion: any potential interest for eventually adopting InitWare?

### ISSUE THREAD

**Issue by marek-lach** [void-linux/void-runit#79]
Hypothetically speaking, a more lightweight, BSD-compatibile SystemD fork is in the works: https://github.com/InitWare/InitWare

What does the Void Linux community at large think about it's potential for fitting it into the Void's BSD inspired philosophy at a later date, over the current _runit_?

**Comment by Vaelatern** [comment]
We would need a reason to switch. I personally enjoy runit's simplicity for my system administration.

If it supports musl and all our platforms, maybe we *could* switch.

**Comment by q66** [comment]
i'd be against switching even if we could

**Comment by ericonr** [comment]
A much easier transition and with more immediate benefits would be `s6-rc`, IMO.

InitWare seems like it covers only parts of systemd functionality haphazardly and managed to switch to a worse build system.

Until

> InitWare isn't ready to use yet!! Unless you are doing so for fun, to experiment, or to contribute, you most likely do not want to try to install InitWare until a first stable release is made!

is removed from their README, I don't think this discussion even makes sense; we don't know the final shape of the software.
