### ISSUE TITLE
wpa_supplicant can't run in zsh/sh default shell

### ISSUE THREAD

**Issue by ayoubelmhamdi** [void-linux/void-runit#83]
I found a **_bug_** in the **config** file of the service named `wpa_supplicant`, when using some shell, like `sh` or `zsh`  instead of `bash` for the `root` user 
```shell
$ cat /etc/passwd

root:x:0:0:root:/root:/bin/zsh
```
this error is in this file : `/etc/sv/wpa_supplicant/auto`
-  Because in bash, we can find in two directories like that
```shell

for f in /etc/wpa_supplicant/wpa_supplicant-*.conf /etc/wpa_supplicant-*.conf ; 
do 
   #....
done
```
but we can't do it in another shell
- my `PR` is changing this `for-loop` or adding `bash shebang`,  

 ***but can't find `Void-Linux source in GitHub***
or where is  this file : `/etc/sv/wpa_supplicant/auto`  send a pull request to fix it

**Comment by Vaelatern** [comment]
I believe this issue isn't an issue.

Can you please confirm, @ayoubelmhamdi ?

**Comment by ayoubelmhamdi** [comment]
> The root shell does not matter the run script has a `/bin/sh` shebang. This should also work in all shells that are somewhat posix compliant, this includes zsh. POSIX shell for loops just take a number of words and loop through them, the patterns are expanded earlier and generally behave like arguments for a normal command.
- in zsh:
```zsh
$ for f in /etc/wpa_supplicant/wpa_supplicant-*.conf /etc/wpa_supplicant-*.conf ; do echo $f;done
zsh: no matches found: /etc/wpa_supplicant-*.conf
```
- in bash:
```bash
$ for f in /etc/wpa_supplicant/wpa_supplicant-*.conf /etc/wpa_supplicant-*.conf ; do echo $f;done
/etc/wpa_supplicant/wpa_supplicant-wlan0.conf
/etc/wpa_supplicant-*.conf
```

**Comment by Duncaen** [comment]
Ok so it doesn't work in zsh, but we are not using zsh for that anyways, so I don't really see what the issue is here.
