### ISSUE TITLE
vlogger: Potential crash on startup

### ISSUE THREAD

**Issue by jdbourbaki** [void-linux/void-runit#85]
I haven't tried to produce this crash, but I did notice that there is a potential segfault in [these lines of code](https://github.com/void-linux/void-runit/blob/5b18be19e3faa8eb396c0608906fbf0d755a4491/vlogger.c#L97-L98):

`if ((p = strrchr(pwd, '/')) && strncmp(p+1, "log", 3) == 0 &&`
`   (*p = '\0', (p = strrchr(pwd, '/'))) && (*(p+1) != '\0')) {`

If someone decided to `exec` vlogger as `./run` from within the directory '/log' then the second call to `strrchr` above should pass an empty string as the first argument and so this second invocation of `strrchr` should return a null pointer and then the code `(*(p+1) != '\0'))` at the end would be expected to segfault.

**Comment by leahneukirchen** [comment]
If strrchr returns NULL, the && is false and shortcuts.

**Comment by jdbourbaki** [comment]
Ah, indeed; I should have read the parentheses a bit more carefully.

My apologies.
