### ISSUE TITLE
recovery /var/service after deleting by mistake

### ISSUE THREAD

**Issue by ayoubelmhamdi** [void-linux/void-runit#86]
I delete the directory called `/var/service` , but void Linux can't boot anymore,
how  can recreate this folder again, because I try this why but not working  
- booting from grub with `linux  /boot/vmlinuz-5.. root=.... rw loglevel=4 init=/bin/bash`
- then
```bash
$ mkdir /var/service
$ ln -s /etc/agetty-tty1 /var/service
```

**Comment by ayoubelmhamdi** [comment]
it stopped at 
```
runnit: leave stage: /etc/runnit/1
runnit: enter stage: /etc/runnit/1
runsvchdir: default: current.

```

**Comment by leahneukirchen** [comment]
It is a symlink by default `lrwxrwxrwx 1 root root 29 Nov 23 14:43 /var/service -> ../run/runit/runsvdir/current`.

Force installing runit should also fix it.

**Comment by ayoubelmhamdi** [comment]
after reinstalling  `runit`
```shell
$ xbps-install -f runit
```
it not look like a directory to link services inside this direcory
```
$ ls /var/service
lrwxrwxrwx 1 root root 29 Nov 23 14:43 /var/service -> ../run/runit/runsvdir/current
```
```shell
$ ls /var/service/
no such file or directory
```

**Comment by leahneukirchen** [comment]
The dir will only exist on a booted systems.  Restore your symlinks to /etc/runit/runsvdir/default

**Comment by ayoubelmhamdi** [comment]
it's work
thank you so much
