### ISSUE TITLE
NetworkManager does not stop correct on runit-shutdown

### ISSUE THREAD

**Issue by dataCobra** [void-linux/void-runit#96]
I use the `dispatcher.d` functionality from NetworkManager for mounting my NAS when I connect to the correct wifi via UUID. When the NetworkManager stops, the `pre-down` function from the dispatcher gets triggered and unmounts the NAS safely before disconnecting from the wifi.

This works as expected when I use `sv "down, stop or force-stop" NetworkManager` on the running system.

When the NM service stops on runit-shutdown however, the `pre-down` seems to **not** get triggered.

The shutdown process seems to try to unmount the mountpoint of the NAS but can't do it safely because it can no longer reach the NAS it the network. The shutdown process takes ~5 minutes in this situation because the unmount gives up after sometime.

To check this I let `rc.shutdown` output STDOUT from `mount` and I could see the NAS mountpoint was still there after the services stopped.

We talked alot about this in the irc channel but couldn't figure out why this happens.

I hope we can find a solution this way.

If you need more information just ask. :+1: 

Regards,
Ben

**Comment by Piraty** [comment]
what solved it for you?

**Comment by dataCobra** [comment]
I'm no longer using this method for more then one year and that's why I closed this issue now.
